/* tslint:disable */
// @ts-nocheck
const { writeFileSync, existsSync, mkdirSync } = require('fs');
const { argv } = require('yargs');

require('dotenv').config();
const environment = argv.environment;

const spaceId =
  process.env.spaceId ||
  process.env.CONTENTFUL_SPACE_ID ||
  process.env.VITE_CONTENTFUL_SPACE_ID;
const token =
  process.env.token ||
  process.env.CONTENTFUL_DELIVERY_TOKEN ||
  process.env.CONTENTFUL_ACCESS_TOKEN ||
  process.env.VITE_CONTENTFUL_ACCESS_TOKEN;

if (!spaceId || !token) {
  console.error(
    'Missing Contentful credentials.\n' +
      'Local: create a .env file in the project root with:\n' +
      '  spaceId=<your-contentful-space-id>\n' +
      '  token=<your-contentful-delivery-token>\n' +
      'Netlify: set the same keys under Site settings → Environment variables\n' +
      '  (enable for Production, Deploy previews, and Branch deploys).',
  );
  process.exit(1);
}

const envDirectory = './src/environments';

if (!existsSync(envDirectory)) {
  mkdirSync(envDirectory);
}

const isProduction = environment === 'prod';
const targetPath = isProduction
  ? './src/environments/environment.prod.ts'
  : './src/environments/environment.ts';

const environmentFileContent = `
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  export const environment = {
    production: ${isProduction},
    contentful: {
      spaceId: '${spaceId}',
      token: '${token}',
    },
  };
`;

writeFileSync(targetPath, environmentFileContent);
console.log(`wrote variables to ${targetPath}`);

/* tslint:enable */
